services:
  click2mask:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - USERNAME=${USER:-appuser}
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UVICORN_LOG_LEVEL=debug
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - type: bind
        source: ..
        target: /app
        consistency: cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ipc: host
    restart: unless-stopped
    tty: true
    stdin_open: true
    user: ${UID:-1000}:${GID:-1000}